In [13]:
import numpy as np

In [14]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 10, 10, 10, 10])

In [15]:
x - y

array([-9, -8, -7, -6, -5])

In [16]:
x + y

array([11, 12, 13, 14, 15])

In [17]:
x * y

array([10, 20, 30, 40, 50])

In [18]:
x / y

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [19]:
x // y

array([0, 0, 0, 0, 0])

In [23]:
np.divide(x, y)

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [24]:
x

array([1, 2, 3, 4, 5])

In [32]:
np.int8(x)

array([1, 2, 3, 4, 5], dtype=int8)

In [52]:
y = np.array([10, 10, 10, 10, 10])

In [53]:
x = np.array([1, 2, 3, 4, 5])

In [54]:
np.matmul(x, y)

150

In [55]:
np.kron(x, y)

array([10, 10, 10, 10, 10, 20, 20, 20, 20, 20, 30, 30, 30, 30, 30, 40, 40,
       40, 40, 40, 50, 50, 50, 50, 50])

In [56]:
np.random.random((10, 2))

array([[0.67421295, 0.59610477],
       [0.33909145, 0.34429995],
       [0.6106629 , 0.71122903],
       [0.13394192, 0.0551345 ],
       [0.54783538, 0.77048268],
       [0.52920374, 0.46437096],
       [0.58968341, 0.66925235],
       [0.73254977, 0.36356083],
       [0.04938723, 0.06288073],
       [0.57382792, 0.43094187]])

In [57]:
np.set_printoptions(precision=1, suppress=True)

In [58]:
np.random.random((10, 2))

array([[0.4, 0.4],
       [0.9, 0.2],
       [1. , 0.2],
       [0.7, 0.4],
       [0. , 0.5],
       [0.1, 0.3],
       [0.6, 0.7],
       [0.4, 0.5],
       [0.8, 0.9],
       [0.4, 0.8]])

In [59]:
import os

In [60]:
os.listdir()

['PIL1.ipynb',
 'Ex2.ipynb',
 'MatTut1.ipynb',
 'data.txt',
 'Untitled.ipynb',
 'Ex1.ipynb',
 '.ipynb_checkpoints']

In [64]:
data = np.loadtxt('data.txt', dtype='<U16', delimiter=',', skiprows=0)

In [65]:
data

array('asd', dtype='<U16')

In [66]:
x

array([1, 2, 3, 4, 5])

In [67]:
x.sum

<function ndarray.sum>

In [68]:
x.sum()

15

In [69]:
y.sum()

50

In [70]:
np.sum((x, y))

65

In [71]:
x

array([1, 2, 3, 4, 5])

In [72]:
y

array([10, 10, 10, 10, 10])

In [74]:
np.sum((x, y), axis=1)

array([15, 50])

In [75]:
x = np.arange(10, dtype='complex')

In [76]:
x

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [77]:
x2 = np.arange(10, dtype='int64')

In [78]:
x.itemsize 

16

In [79]:
x2.itemsize

8

In [80]:
x

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

In [81]:
np.mat('1, 2, 3, 4, 5;6, 7, 8, 9, 10')

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [84]:
x = np.array([('Sandaru', 14), ('Nadu', 15)], dtype=[('name', '<U20'), ('Age', 'int')])

In [85]:
x

array([('Sandaru', 14), ('Nadu', 15)],
      dtype=[('name', '<U20'), ('Age', '<i8')])

In [86]:
x = np.arange(20)

In [88]:
np.where(x > 10, 'Ela', 'Pakaya')

array(['Pakaya', 'Pakaya', 'Pakaya', 'Pakaya', 'Pakaya', 'Pakaya',
       'Pakaya', 'Pakaya', 'Pakaya', 'Pakaya', 'Pakaya', 'Ela', 'Ela',
       'Ela', 'Ela', 'Ela', 'Ela', 'Ela', 'Ela', 'Ela'], dtype='<U6')